### PR TITLE
Fix search for "dog -cat" pattern

### LINKED ISSUE #1: Search Issues page which uses postgresql's full text search - special query operators don't seem to work right
The "-" operator, to exclude, doesn't seem to be working.

### PR DESCRIPTION
**Pull request by ghost**
fix #1

image

image

### CODE REVIEW

**Comment by ctrager** [comment]
Did you just reformat the sql or did you change it?

**Comment by ghost** [comment]
> Did you just reformat the sql or did you change it?

ts_rank > ts_rank_cd

where
   websearch_to_tsquery('english', '$') @@ to_tsvector('english', i_description)

where
    websearch_to_tsquery('english', '$') @@ to_tsvector('english', p_text)

**Comment by ghost** [comment]
image

I am using UTF8 encoding for db.

**Comment by ctrager** [comment]
Thanks so much!

**Comment by ghost** [comment]
👍

**Pull request merged**
