### PR TITLE
Migrate "Reports" feature

### PR DESCRIPTION
**Pull request by ghost**
#8

### CODE REVIEW

**Comment by ghost** [comment]
Plese see, I changed _CrudDataTablePartial.

**Comment by ctrager** [comment]
I apologize for being discouraging here, but  I'm not going to review a pull request with 45 files. This needs to be way more focused for me to review it. I was imaging just 3 pages, 2 of them for the crud for the reports, simlar to queries and query, and 1 for actually viewing the report.  Another sql file for the reports.  Changes to the Admin page to get to the reports.  That's about it. The Dashboard, I'm not sure I want that in Budoco.

One of my design goals for Budoco is to keep it smaller so that I don't hate it the way I grew to hate working on BugTracker.NET. It was just too big. 

Also, no image files unless there's a super great reason. One of my design goals for Budoco is just to keep it simple, even cosmetically simple.

Also the change to CrudDataTablePartial are too conflicting. Look at the diff. I've created a few different partials that are very 
"similar but I prefer that not DRY way than making one partial that's so complicated I can't work on it with confidence.

Also, no @Html.Raw allowed unless there's a super great reason for it.

**Comment by ctrager** [comment]
Sorry, but also, not going to review if there are changes in the users and orgs area because that's the area I'm working on now, to add what I think are the minimum number of permissions. There's no reason why the addition of the Report feature should involve changing users and orgs.

**Comment by ghost** [comment]
Ok. I will make completely addable code.
Without dashboards.
Without images.

**Comment by ghost** [comment]
Do you want to use one "Action" column or several?

image
image

**Comment by ctrager** [comment]
One, like elsewhere in budoco

**Comment by ghost** [comment]
What is the correct way to check the permissions now?

```
if (security.user.is_admin || security.user.can_use_reports)
{
    //
}
else
{
    Response.Write ("You are not allowed to use this page.");
    Response.End();
}
```

```
if (security.user.is_admin || security.user.can_edit_reports)
{
    //
}
else
{
    Response.Write ("You are not allowed to use this page.");
    Response.End();
}
```

**Comment by ctrager** [comment]
For restricted pages: 
bd_util.check_user_permissions(HttpContext, bd_util.MUST_BE_ADMIN);
otherwise just to make sure user is logged on:
 bd_util.check_user_permissions(HttpContext);

**Comment by ghost** [comment]
I can split it into multiple commits if needed.

**Comment by ctrager** [comment]
Questions:
1) Does the dotfile need to be part of the pull request? If not, can you remove it?2
2) What exactly is different about the ReportDataTablePartial from the other partials? I would think you could use the same one that the queries use.  If not, why not?

**Comment by ghost** [comment]
> Does the dotfile need to be part of the pull request? If not, can you remove it?

Ok. I am using VS, it adds managed files.
[gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore)

> What exactly is different about the ReportDataTablePartial from the other partials? I would think you could use the same one that the queries use. If not, why not?

No need actions. No need special formatting for columns. Needs message when empty rows.

**Comment by ctrager** [comment]
Are you done?

**Comment by ghost** [comment]
Yes.

**Comment by ctrager** [comment]
You like the dark theme!

**Comment by ghost** [comment]
Is that a question? :)

**Comment by ctrager** [comment]
No, i'm just reacting to the black background. It's fine.  Just curious why #0e0e0e and not all the way to #000000?  Can you tell the difference? I'm just curious, not criticizing.

**Comment by ghost** [comment]
I don't think I understand what this is about. In general, I can distinguish these colors.

**Comment by ghost** [comment]
Ah, I got it! This is the background color of the site.
Try to disable the property.

image

**Pull request merged**
